version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (net/http.ResponseWriter).Write
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: blank-imports
        - name: exported
        - name: unreachable-code
        - name: unused-parameter
  exclusions:
    rules:
      - linters: [errcheck]
        source: '\.Body\.Close\(\)'

issues:
  max-same-issues: 0

formatters:
  enable:
    - goimports
